version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess_arena
    ports:
      - "5432:5432" # Expose the db port for local development if needed
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

  app:
    build: . # Build from the Dockerfile in the current directory
    ports:
      - "3000:3000" # Expose the application port
    environment:
      POSTGRES_URL: postgres://postgres:postgres@db:5432/chess_arena # use the db service name
      FRONTEND_URL: "" # set your frontend url.
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      JWT_SECRET: stronger-jwt-secret-for-production
      LOG_LEVEL: debug
      PORT: 3000 # ensure port is set in docker compose as well.
    depends_on:
      - db
    # Use network mode host if needed, but it is not recommended for production.
    # network_mode: host

volumes:
  postgres-data: # Define the named volume
